### PR TITLE
updates for MM 4.9

### PR DESCRIPTION
**Pull request by tejaycar**

### CODE REVIEW

**Comment by tejaycar** [comment]
@drnic  Can you kick off the publish on this when you have the chance (or is that automated now?)
Thanks

**Comment by drnic** [comment]
Crap. I accidentally pressed Delete button. Lol. Sorry! Can you please push again. I’m so sorry!

**Comment by drnic** [comment]
The Delete button is huge!

**Comment by tejaycar** [comment]
I already merged the request to master.  I just need a new release cut from
master.

**Pull request merged**
