### PR TITLE
Mm4.2

### PR DESCRIPTION
**Pull request by tejaycar**

### CODE REVIEW

**Comment by jhunt** [comment]
@tejaycar can you look at the merge conflicts on this one?

**Comment by tejaycar** [comment]
Yes, I'll look Monday.  I think they're phantoms..

**Comment by drnic** [comment]
@tejaycar @jhunt helping out, I fixed the branch + merged. The release notes have the 4.1 + 4.2 notes merged together. @tejaycar can you confirm the release notes look good?

**Comment by tejaycar** [comment]
I think we just need the 4.2 notes, since the prior release had the 4.1
notes.  But either way should be fine.

**Comment by drnic** [comment]
I don't think we've cut a release since you started updating the job properties https://github.com/cloudfoundry-community/mattermost-boshrelease/releases

I'll cut a release now

**Comment by tejaycar** [comment]
Ah, ok.  That's perfect.

**Pull request merged**
