### PR TITLE
Mm4.1

### PR DESCRIPTION
**Pull request by tejaycar**

### CODE REVIEW

**Comment by drnic** [comment]
@tejaycar lovely; can I ask you to create a `ci/release_notes.md` describing the changes? These will go straight into the github release notes when I run shipit in the CI.

Thanks in advance!

**Comment by tejaycar** [comment]
@drnic Yea, we can do that.  However, there is one other issue.  I'm still not clear on how to ensure you ship the same blobs I'm using.

For each release, we should pull the coordinated MM blob (in this case MM 4.1) and the latest load test blob

the load test blob is always available at https://releases.mattermost.com/mattermost-load-test/mattermost-load-test.tar.gz (sadly no versioning at this time)
I believe the Ci scripts already handle the correct upload for the MM code.

**Comment by drnic** [comment]
Ok, I've created a new repo +github releases https://github.com/starkandwayne/mattermost-releases/releases

I'll update this pipeline next/later. Am on holidays so am squeezing this in. BBl

**Comment by drnic** [comment]
@tejaycar I've upgraded the CI to bump enterprise + load-test to v4.2.0 (and should keep doing this in future). Would you like rebase this PR?

**Comment by drnic** [comment]
Ooh, the `MM4.1` branch is in this repo so I've fixed the branch and force pushed

**Comment by drnic** [comment]
@tejaycar ok this branch is now CI happy; but we've moved to 4.2.0 blobs; would you like it merged as is or want to upgrade for any new 4.2 properties?

**Comment by drnic** [comment]
Tell you what, I'll merge this PR so its all on master. And any 4.2.0 fields can go into new PR.

**Comment by tejaycar** [comment]
OK, that will have to do :)
4.2 PR should be out momentarily

**Pull request merged**
